name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        nim: [1.6.20, stable]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nim
      uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nim }}

    - name: Nimble check
      run: nimble check

    - name: Nimble install
      run: nimble install -y

  status:
    if: always()
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')  || contains(needs.*.result, 'skipped') }}
        run: exit 1
